{% set version = "1.2.4" %}

package:
  name: pyside
  version: {{ version }}

source:
  fn: PySide-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/P/PySide/PySide-{{ version }}.tar.gz
  sha256: 1421bc1bf612c396070de9e1ffe227c07c1f3129278bc7d30c754b5146be2433
  patches:
    # eliminate spurious shiboken stderr output to avoid the 4MB log limit on Travis
    # https://codereview.qt-project.org/#/c/172582/
    - shiboken-osx-fix-stderr-output.patch
    # https://github.com/sparsehash/sparsehash/commit/7b8afad35bd601ea780b0f72e215de96613d3c95
    # https://codereview.qt-project.org/#/c/172583/
    - fix-vc2013-hash_map.patch
    # https://bugreports.qt.io/browse/PYSIDE-321
    # Backported https://code.qt.io/cgit/pyside/pyside.git/commit/?id=23d77136da1f249f0a78c8c7e8124adc8c604230
    - fix-vs2015-4.8.patch
    # make the testsuite pass
    - disable-failing-tests.patch
    # https://bugreports.qt.io/browse/PYSIDE-103
    - wrapinstance-overflow.patch
    # https://github.com/looooo/pivy/issues/18
    - win_pointer_conversion_fix.patch  # [win]

build:
  number: 9
  detect_binary_files_with_prefix: True

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - qt
    - libxslt
  run:
    - python
    - qt
    - libxslt

test:
  imports:
    - PySide.QtCore
    - PySide.QtDeclarative
    - PySide.QtGui
    - PySide.QtHelp
    - PySide.QtMultimedia
    - PySide.QtNetwork
    - PySide.QtScript
    - PySide.QtScriptTools
    - PySide.QtSql
    - PySide.QtSvg
    - PySide.QtTest
    - PySide.QtUiTools
    - PySide.QtWebKit
    - PySide.QtXml
    - PySide.QtXmlPatterns
    - PySide.QtOpenGL
    - PySide.phonon  # [not linux]
    - pysideuic
  commands:
    - pyside-lupdate -help
    - pyside-uic -help

about:
  home: https://wiki.qt.io/PySide
  license: LGPL3
  license_file: sources/pyside/COPYING
  summary: Python bindings for Qt

extra:
  recipe-maintainers:
    - jschueller
    - ccordoba12
